name: Rspec

on:
  push:
    paths:
      - "api"

env:
  RUBY_VERSION: 2.7.1
  RAILS_ENV: test

jobs:
  setup-Rspec:
    name: Rspec
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup docker
        shell: bash
        run: |
          docker-compose run api yarn install --check-files
          docker-compose run api yarn upgrade
          docker-compose build
          docker-compose run api rake db:create
        env:
          RAILS_ENV: test

      - name: Run RSpec
        shell: bash
        run: |
          docker-compose run api bundle exec rspec
        env:
          RAILS_ENV: test
