name: Rspec

on:
  push:
    paths:
      - "api"

env:
  RUBY_VERSION: 2.7.1
  RAILS_ENV: test

jobs:
  setup-Rspec:
    name: Rspec
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Test with Rspec
        run: |
          cd api
          gem install bundler
          bundle install
          bundle exec rspec
