name: test

on: push


jobs:
  exec-spec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker build
        run: | 
          make up

      - name: setup backend
        env:
          RAILS_ENV: test
        run: | 
          make db_create  

      - name: exec migrate
        run: | 
          make migrate     

      - name: exec rspec
        run: |
          make test